In [9]:
import numpy as np

# 1.
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

# 2.
ones_array = np.ones((4, 2))
print("\nAll Ones Array (4x2):\n", ones_array)

# 3.
full_array = np.full((3, 3), 7)
print("\nFull Array (3x3 filled with 7):\n", full_array)

# 4.
given_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros Like Given Array:\n", zeros_like_array)

# 5.
ones_like_array = np.ones_like(given_array)
print("\nOnes Like Given Array:\n", ones_like_array)

# 6.
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array:\n", numpy_array)

Empty Array (2x2):
 [[1.14e-322 2.52e-322]
 [6.42e-323 1.43e-322]]

All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full Array (3x3 filled with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros Like Given Array:
 [[0 0]
 [0 0]]

Ones Like Given Array:
 [[1 1]
 [1 1]]

Converted NumPy Array:
 [1 2 3 4]


In [10]:
import numpy as np
# 1.
array1 = np.arange(10, 50)
print("Array from 10 to 49:\n", array1)

# 2.
matrix3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix (0 to 8):\n", matrix3x3)

# 3.
identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)

# 4.
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array of size 30:\n", random_array)
print("Mean of array:", mean_value)

# 5.
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array:\n", random_10x10)
print("Min value:", min_value, "Max value:", max_value)

# 6.
zero_array = np.zeros(10)
zero_array[4] = 1  # index starts from 0
print("\nZero array with 5th element as 1:\n", zero_array)

# 7.
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:\n", reversed_arr)

# 8.
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:\n", border_array)

# 9.
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard pattern:\n", checkerboard)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix (0 to 8):
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random Array of size 30:
 [0.7822027  0.23041812 0.09893031 0.56991103 0.83518224 0.0244517
 0.17987196 0.72038047 0.12234939 0.59380585 0.40148851 0.71854336
 0.58541737 0.8537662  0.48447704 0.25639225 0.7868155  0.39903714
 0.72134676 0.15394959 0.77588462 0.918946   0.55466138 0.91125942
 0.75266453 0.00825119 0.86894347 0.30213091 0.48756788 0.50835377]
Mean of array: 0.5202466885533931

10x10 Random Array:
 [[0.47758953 0.42693759 0.68007801 0.37550446 0.6846167  0.79958338
  0.03228289 0.15021596 0.13686234 0.92895602]
 [0.15107617 0.32602057 0.46830701 0.78054883 0.30561583 0.16913973
  0.44462597 0.49935728 0.62351982 0.3591755 ]
 [0.4265931  0.00238617 0.49918842 0.63460542 0.78928687 0.07877934
  0.02808061 0.09523568 0.53

In [11]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1.
add_xy = x + y
print("x + y:\n", add_xy)

# 2.
sub_xy = x - y
print("\nx - y:\n", sub_xy)

# 3.
mult_x = x * 3
print("\nx * 3:\n", mult_x)

# 4.
square_x = x ** 2
print("\nx squared:\n", square_x)

# 5.
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("\nDot product v.w:", dot_vw)
print("Dot product x.v:\n", dot_xv)
print("Dot product x.y:\n", dot_xy)

# 6.
concat_row_xy = np.concatenate((x, y), axis=0)
concat_col_vw = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

print("\nConcatenate x and y along rows:\n", concat_row_xy)
print("Concatenate v and w along columns:\n", concat_col_vw)

# 7.
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenate x and v:\n", concat_xv)
except ValueError as e:
    print("\nError concatenating x and v:", e)
    print("Explanation: x is a 2x2 matrix and v is a 1D array of length 2. Dimensions do not match along axis=1 for row-wise concatenation, hence it throws an error.")

x + y:
 [[ 6  8]
 [10 13]]

x - y:
 [[-4 -4]
 [-4 -3]]

x * 3:
 [[ 3  6]
 [ 9 15]]

x squared:
 [[ 1  4]
 [ 9 25]]

Dot product v.w: 219
Dot product x.v:
 [29 77]
Dot product x.y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]

Error concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: x is a 2x2 matrix and v is a 1D array of length 2. Dimensions do not match along axis=1 for row-wise concatenation, hence it throws an error.


In [12]:
import numpy as np

# Given Arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1.
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("1. A × A⁻¹:\n", identity_check)


# 2.
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("AB equal to BA?", np.array_equal(AB, BA))


# 3.
AB_transpose = (np.dot(A, B)).T
BT_AT = np.dot(B.T, A.T)
print("\n3. (AB)ᵀ:\n", AB_transpose)
print("BᵀAᵀ:\n", BT_AT)
print("Are they equal?", np.array_equal(AB_transpose, BT_AT))


# 4.
# Equations:
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

# Using inverse
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)
print("\n4. Solution using inverse [x, y, z]:", X)

# Optional: Solve using np.linalg.solve (more efficient)
X_solve = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve [x, y, z]:", X_solve)

1. A × A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB equal to BA? False

3. (AB)ᵀ:
 [[23 51]
 [13 29]]
BᵀAᵀ:
 [[23 51]
 [13 29]]
Are they equal? True

4. Solution using inverse [x, y, z]: [ 2.  1. -2.]
Solution using np.linalg.solve [x, y, z]: [ 2.  1. -2.]
